### ISSUE TITLE
Add new "previewscore" column to "Submission" database table

### ISSUE THREAD

**Issue by danstowell** [julj/submission#6]
As per email discussion: we want there to be two scores not one - a "preview" score and the real score that will be used in the end. So, we need to add a "previewscore" column.

I don't know how the db code works here but maybe it's as simple as adding a line after this one: https://github.com/julj/submission/blob/master/app/models.py#L62

But a big issue is: how to handle the files that have already been submitted? What goes in that new column, for them? We could recalculate new scores, as indicated by Herve. I suggest that a simple fallback option is simply to copy the value from "score"->"previewscore" at the moment that the new column is created.

@julj, you may need to comment on what is feasible at this point.

**Comment by julj** [comment]
Added in 72c2ddca3bee0e6a8bacd07958b83438dc240397
